version: 1.0.8.{build}

for:
  -
    branches:
      only:
        - master
    build:
      verbosity: minimal
    artifacts:
      - path: AMKFF_latest.zip
    deploy:
      provider: FTP
      confirm-deploy: true
  -
    branches:
      only:
        - bleeding-edge
    build:
      verbosity: minimal
    artifacts:
      - path: AMKFF_latestbeta.zip
    deploy:
      provider: FTP
      confirm-deploy: true
  -
    branches:
      except:
        - master
        - bleeding-edge
    only_commits:
      files:
        - src/
        - .appveyor.yml
    build:
      verbosity: minimal
    artifacts:
      - path: AMKFF_testbuild.zip
    deploy:
      provider: FTP
      confirm-deploy: false

configuration: Release

after_build:
  - ps: .\zip_script.ps1
  
deploy:
  provider: FTP
  on:
    confirm-deploy: true
  protocol: sftp
  host: www.atarismwc.com
  folder: html/amkff_releases/
  username: pi
  password:
    secure: N90u+68BQTm8IHH9p3O78A==
